name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Install and Build
        run: |
          cd Frontend
          npm ci
          npm run build
        env:
          VITE_APP_URL: https://ai-resume-builder-backend.onrender.com/

      - name: Copy root index.html to dist
        run: |
          cp index.html Frontend/dist/
          cp -r Frontend/dist/* dist/ || mkdir -p dist && cp -r Frontend/dist/* dist/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
